---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Inicio
    url: "/home.html"
  - title: Notas de la versión
    url: "/releasenotes.html"
  - title: Comience a usar XCP
    url: "/index.html"
    type: solutions
    entries:
    - title: Funciones complementarias XCP NFS
      url: "/xcp-nfs-add-ons.html"
    - title: Funciones no admitidas
      url: "/xcp-unsupported-features.html"
    - title: Configuraciones admitidas
      url: "/xcp-supported-configurations.html"
    - title: Puertos utilizados por XCP
      url: "/xcp-ports-used.html"
  - title: Instale XCP
    url: "/xcp-install-xcp.html"
    entries:
    - title: Preparación de Linux para XCP NFS
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: Prepare Windows para XCP SMB
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: Preparar análisis de archivos
      url: "/xcp-prepare-file-analytics.html"
    - title: Instale XCP NFS
      url: "/xcp-install-xcp-nfs.html"
    - title: Instale XCP SMB
      url: "/xcp-install-xcp-smb.html"
    - title: Instale File Analytics para NFS
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: Instale File Analytics para SMB
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: Configurar XCP
    entries:
    - title: Configure el archivo INI para XCP NFS
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: Ajuste del rendimiento
      url: "/xcp-performance-tuning.html"
    - title: Variable de entorno
      url: "/xcp-environment-variable.html"
    - title: Configure el conector POSIX
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: Configurar el conector HDFS
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: Configure el escalado horizontal multinodo
      url: "/xcp-configure-multinode-scaleout-nfs.html"
  - title: Planificación de la migración de datos
    url: "/xcp-plan-data-migration.html"
    entries:
    - title: Planifique la migración de datos NFS
      url: "/xcp-plan-nfs-data-migration.html"
    - title: Planifique la migración de datos de SMB
      url: "/xcp-plan-smb-data-migration.html"
    - title: Planificar mediante Análisis de archivos
      url: "/xcp-using-file-analytics.html"
      entries:
      - title: Acceda a File Analytics
        url: "/xcp-access-file-analytics.html"
      - title: Agregar servidores de archivos
        url: "/xcp-add-file-servers.html"
      - title: Ejecute una exploración
        url: "/xcp-run-a-scan.html"
    - title: Filtros
      url: "/xcp-filters.html"
    - title: Registro para NFS y SMB (opcional)
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: Migración de datos
    entries:
    - title: Migre datos NFS
      url: "/xcp-migrate-nfs-data.html"
    - title: Migre datos de SMB
      url: "/xcp-migrate-smb-data.html"
    - title: Funciones NFS adicionales
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: Solucionar problemas
    entries:
    - title: Solucionar errores de XCP NFS
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: Resolución de problemas de errores XCP SMB
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: Solucionar errores de análisis de archivos XCP
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: Obtenga más información
    url: "/get-more-information.html"
