---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentación de XCP de NetApp
    url: "/index.html"
  - title: Notas de la versión
    url: "/releasenotes.html"
  - title: Comience a usar XCP
    entries:
    - title: Más información sobre XCP
      url: "/xcp-index.html"
    - title: Funciones complementarias XCP NFS
      url: "/xcp-nfs-add-ons.html"
    - title: Funciones no admitidas
      url: "/xcp-unsupported-features.html"
    - title: Configuraciones admitidas
      url: "/xcp-supported-configurations.html"
    - title: Puertos utilizados por XCP
      url: "/xcp-ports-used.html"
  - title: Instale XCP
    entries:
    - title: Prepárese para la instalación de XCP
      url: "/xcp-install-xcp.html"
    - title: Preparación de Linux para XCP NFS
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: Prepare Windows para XCP SMB
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: Preparar análisis de archivos
      url: "/xcp-prepare-file-analytics.html"
    - title: Instale XCP NFS
      url: "/xcp-install-xcp-nfs.html"
    - title: Instale XCP SMB
      url: "/xcp-install-xcp-smb.html"
    - title: Instale File Analytics para NFS
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: Instale File Analytics para SMB
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: Configurar XCP
    entries:
    - title: Configure el archivo INI para XCP NFS
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: Ajuste del rendimiento
      url: "/xcp-performance-tuning.html"
    - title: Variable de entorno
      url: "/xcp-environment-variable.html"
    - title: Configure el conector POSIX
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: Configurar el conector HDFS
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: Configure el escalado horizontal multinodo
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: Configure el conector S3
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: Planificación de la migración de datos
    entries:
    - title: Descripción general
      url: "/xcp-plan-data-migration.html"
    - title: Planifique la migración de datos NFS
      url: "/xcp-plan-nfs-data-migration.html"
    - title: Planifique la migración de datos de SMB
      url: "/xcp-plan-smb-data-migration.html"
    - title: Planifique la migración de datos HDFS
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: Planificar mediante Análisis de archivos
      entries:
      - title: Planificar la migración de los datos
        url: "/xcp-file-analytics-plan-data-migration.html"
      - title: Acceda a File Analytics
        url: "/xcp-access-file-analytics.html"
      - title: Agregar servidores de archivos
        url: "/xcp-add-file-servers.html"
      - title: Ejecute una exploración
        url: "/xcp-run-a-scan.html"
    - title: Filtros
      url: "/xcp-filters.html"
    - title: Registro para NFS y SMB (opcional)
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: Migración de datos
    entries:
    - title: Migre datos NFS
      url: "/xcp-migrate-data.html"
    - title: Migre datos de SMB
      url: "/xcp-migrate-smb-data.html"
    - title: Migración de flujos de datos alternativos NTFS para SMB
      entries:
      - title: Migración de flujos de datos alternativos NTFS para SMB
        url: "/xcp-smb-ads.html"
    - title: Migrar datos de HDFS
      url: "/xcp-migrate-hdfs-data.html"
    - title: Ejecute varios trabajos XCP en el mismo host
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: Funciones NFS adicionales
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: Solucionar problemas
    entries:
    - title: Solucionar errores de XCP NFS
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: Solucionar errores de SMB de XCP
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: Solucionar errores de análisis de archivos XCP
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: Referencia XCP
    entries:
    - title: Descripción general de la referencia del comando XCP
      url: "/xcp-reference-overview.html"
    - title: Referencia de comandos de NFS
      entries:
      - title: ayuda
        url: "/xcp-nfs-reference-help.html"
      - title: mostrar
        url: "/xcp-nfs-reference-show.html"
      - title: licencia
        url: "/xcp-nfs-reference-license.html"
      - title: activar
        url: "/xcp-nfs-reference-activate.html"
      - title: escanee
        url: "/xcp-nfs-reference-scan.html"
      - title: copiar
        url: "/xcp-nfs-reference-copy.html"
      - title: sincr
        url: "/xcp-nfs-reference-sync.html"
      - title: reanudar
        url: "/xcp-nfs-reference-resume.html"
      - title: verificación
        url: "/xcp-nfs-reference-verify.html"
      - title: chmod
        url: "/xcp-nfs-reference-chmod.html"
      - title: chown
        url: "/xcp-nfs-reference-chown.html"
      - title: volcado de registros
        url: "/xcp-nfs-reference-logdump.html"
      - title: eliminar
        url: "/xcp-nfs-reference-delete.html"
      - title: estimación
        url: "/xcp-nfs-reference-estimate.html"
      - title: indexdelete
        url: "/xcp-nfs-reference-indexdelete.html"
      - title: isync
        url: "/xcp-nfs-reference-isync.html"
    - title: Referencia de comandos del SMB
      entries:
      - title: ayuda
        url: "/xcp-smb-reference-help.html"
      - title: mostrar
        url: "/xcp-smb-reference-show.html"
      - title: licencia
        url: "/xcp-smb-reference-license.html"
      - title: activar
        url: "/xcp-smb-reference-activate.html"
      - title: escanee
        url: "/xcp-smb-reference-scan.html"
      - title: copiar
        url: "/xcp-smb-reference-copy.html"
      - title: sincr
        url: "/xcp-smb-reference-sync.html"
      - title: verificación
        url: "/xcp-smb-reference-verify.html"
      - title: configurar
        url: "/xcp-smb-reference-configure.html"
      - title: escuche
        url: "/xcp-smb-reference-listen.html"
    - title: Casos de uso de XCP
      entries:
      - title: Casos de uso de XCP
        url: "/xcp-reference-use-cases.html"
    - title: Registro XCP
      entries:
      - title: Establezca la opción logConfig
        url: "/xcp-reference-logging-logconfig.html"
      - title: Defina la opción eventlog
        url: "/xcp-reference-logging-eventlog.html"
      - title: Habilite el cliente syslog
        url: "/xcp-reference-logging-syslog.html"
    - title: Registros de eventos de XCP
      entries:
      - title: Registros de eventos de NFS
        url: "/xcp-reference-event-logs-nfs.html"
      - title: Registros de eventos de SMB
        url: "/xcp-reference-event-logs-smb.html"
  - title: Avisos legales
    url: "/legal-notices.html"
