---
sidebar: sidebar 
permalink: xcp-unsupported-features.html 
keywords: xcp, nfs, smb, features, unsupported, configuration 
summary: Algunas características no son compatibles con XCP NFS o XCP SMB. 
---
= Funciones no admitidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP NFS no admite las siguientes funciones:

[cols="40,60"]
|===
| Nombre de característica | Descripción 


| IPv6 | No admite IP versión 6 (IPv6) 


| Listas de control de acceso (ACL) de NFSv4 (terceros) | No admite ACL de NFSv4 de NetApp 


| Conector POSIX  a| 
* La `sync` El comando no admite el conector POSIX
* No debe utilizar el `copy` cuando el origen está activo




| Linux | XCP ya no es compatible con distribuciones anteriores de Linux que fueron compatibles con XCP 1.6.3. 


| Soporte de código fuente activo | XCP no admite la combinación de operaciones de copias Snapshot básicas o incrementales con migraciones de código activo. 


| Migración de NFS a S3 | XCP no admite la migración de NFS a S3. 
|===
XCP SMB no admite las siguientes funciones:

[cols="40,60"]
|===
| Nombre de característica | Descripción 


| Enlace simbólico de NFS (enlace simbólico) | XCP SMB no admite symlink NFS 


| Opción ACL para la exploración | ACL no compatibles con la opción de análisis 


| IPv6 | No admite IP versión 6 (IPv6) 


| Flujos de datos alternativos NTFS | XCP no admite actualmente flujos de datos alternativos 


| Filtros XCP | La opción excluir SMB XCP actualmente excluye directorios basados en su patrón en el filtro y atraviesa el sistema de archivos de esos directorios. 


| Migración de origen activo | XCP no admite la modificación de datos en el volumen de origen durante la migración. 


| Varias instancias de XCP en el mismo host | Al ejecutar varias instancias de XCP en el mismo host, es posible que obtenga resultados impredecibles. 
|===
Las siguientes características comunes no están disponibles para XCP NFS y SMB:

* *Tiempo para completar la migración*: XCP upfront no proporciona el tiempo para completar la migración o el tiempo para completar cualquier comando usado para la migración. Si realiza la transición final, confirme que la pérdida de datos en el volumen de origen es baja.
* *Ejecutando de nuevo la copia en un destino no limpio*: La copia de línea de base de XCP fallará cuando haya datos parciales en el destino de destino. Para que la copia de la línea de base de XCP sea correcta y la verificación de XCP, el destino debe estar limpio.
* *Live destination*: XCP no admite la modificación de datos en el volumen de destino durante una migración o durante una sincronización incremental.
* *Usuario no raíz para File Analytics*: XCP no admite instalaciones y configuraciones realizadas por un usuario que no sea raíz o un usuario sudo.


Las siguientes características no están disponibles para los conectores del sistema de archivos distribuidos de Hadoop (HDFS):

[cols="2*"]
|===
| Nombre de característica | Descripción 


| Compatibilidad con `sync` comando | El conector HDFS no admite el `sync` comando. 


| Enlace simbólico (symlink) y soporte de enlace duro | El sistema de archivos HDFS no admite enlaces simbólicos, enlaces físicos o archivos especiales. 


| Migración HDFS de origen activo | XCP no admite la modificación de datos en el sistema de archivos HDFS en el origen durante la migración 
|===
Las siguientes funciones no están disponibles para los conectores de Simple Storage Service (S3):

* *Migración con S3 bucket como fuente*: XCP no admite la migración con un bucket S3 como fuente.

