---
sidebar: sidebar 
permalink: xcp-nfs-reference-chmod.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Referencia de comandos NFS XCP 
---
= chmod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El NFS de XCP `chmod` el comando escanea y cambia el permiso de archivo de todos los archivos para la estructura de directorios dada. El comando 'chmod' requiere MODE o REFERENCE, NFS SHARE o POSIX PATH como variable. El XCP `chmod` el comando cambia recursivamente los permisos para una ruta determinada. El resultado del comando muestra el total de archivos escaneados y los permisos modificados en la salida.

.Sintaxis
[source, cli]
----
xcp chmod -mode <value> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -mode <IP address>:/source_vol

Xcp command : xcp chmod -mode <IP address>://source_vol
Stats : 6 scanned, 4 changed mode
Speed : 1.96 KiB in (2.13 KiB/s), 812 out (882/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux] #
----
====
En la siguiente tabla, se muestra el `chmod` parámetros y su descripción.

[cols="2*"]
|===
| Parámetro | Descripción 


| <<nfs_chmod_exclude,chmod -exclude   >> | Excluye los archivos y directorios que coinciden con el filtro. 


| <<nfs_chmod_match,chmod -match   >> | Sólo procesa los archivos y directorios que coinciden con el filtro. 


| <<nfs_chmod_reference,chmod -reference  >> | Especifica el archivo o punto de directorio al que se hace referencia. 


| <<nfs_chmod_v,chmod -v >> | Informa de la salida de cada objeto procesado. 
|===


== chmod -excluir <filter>

Utilice la `-exclude <filter>` con el `chmod` comando para excluir los archivos y directorios que coinciden con el filtro.

.Sintaxis
[source, cli]
----
xcp chmod -exclude <filter> -mode <value> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -exclude "fnm('3.img')" -mode 770 101.11.10.10:/s_v1/D3/

Excluded: 1 excluded, 0 did not match exclude criteria
Xcp command : xcp chmod -exclude fnm('3.img') -mode 770 101.11.10.10:/s_v1/D3/
Stats : 5 scanned, 1 excluded, 5 changed mode
Speed : 2.10 KiB in (7.55 KiB/s), 976 out (3.43 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chmod -match <filter>

Utilice la `-match <filter>` con el `chmod` comando para procesar sólo los archivos y directorios que coinciden con el filtro.

.Sintaxis
[source, cli]
----
xcp chmod -match <filter>  -mode <value> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -match "fnm('2.img')" -mode 777 101.11.10.10:/s_v1/D2/

Filtered: 1 matched, 5 did not match
Xcp command : xcp chmod -match fnm('2.img') -mode 101.11.10.10:/s_v1/D2/
Stats : 6 scanned, 1 matched, 2 changed mode
Speed : 1.67 KiB in (1.99 KiB/s), 484 out (578/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]
----
====


== chmod -reference <reference>

Utilice la `-reference <reference>` con el `chmod` comando para especificar el archivo o punto de directorio al que se hace referencia.

.Sintaxis
[source, cli]
----
xcp chmod -reference <reference> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -reference 101.11.10.10:/s_v1/D1/1.txt 102.21.10.10:/s_v1/D2/

Xcp command : xcp chmod -reference 101.11.10.10:/s_v1/D1/1.txt 102.21.10.10:/s_v1/D2/
Stats : 6 scanned, 6 changed mode
Speed : 3.11 KiB in (3.15 KiB/s), 1.98 KiB out (2.00 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chmod -v

Utilice la `-v` con el `chmod` comando para informar de la salida de cada objeto procesado.

.Sintaxis
[source, cli]
----
chmod -mode <value> -v <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -mode 111 -v file:///mnt/s_v1/D1/

mode of 'file:///mnt/s_v1/D1' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/1.txt' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/softlink_1.img' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/softlink_to_hardlink_1.img' changed from 0777 to 0111 mode
of 'file:///mnt/s_v1/D1/1.img' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/hardlink_1.img' changed from 0777 to 0111 mode of
'file:///mnt/s_v1/D1/1.img1' changed from 0777 to 0111
Xcp command : xcp chmod -mode 111 -v file:///mnt/s_v1/D1/ Stats : 7 scanned, 7
changed mode
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====