---
sidebar: sidebar 
permalink: xcp-migrate-hdfs-data.html 
keywords: netapp, xcp, migrate, data, nfs, hdfs, smb, copy, resume, verify, posix 
summary: Migrar datos de HDFS 
---
= Migrar datos de HDFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Tras planificar la migración con `scan` Puede migrar los datos HDFS.



== Copiar

La `copy` El comando analiza y copia todos los datos de origen del sistema de archivos distribuidos de Hadoop (HDFS) en un bloque NFS o Simple Storage Service (S3). La `copy` comando requiere tener rutas de origen y destino como variables. Al final de la operación de copia, se muestran los detalles de los archivos escaneados y copiados, el rendimiento, la velocidad y el tiempo transcurrido.

*Ejemplo de ruta NFS:*

[listing]
----
xcp copy -newid <id> hdfs:///demo/user dst_server:/dst_export
----
*Ejemplo de ruta POSIX:*

[listing]
----
xcp copy -newid <id> hdfs:///demo/user file:///mnt/dest
----
*Ejemplo de ruta S3:*

[listing]
----
xcp copy -newid <id> hdfs:///demo/user s3://my-bucket
xcp copy -newid <id> -s3.profile <s3 profile name> -s3.endpoint <endpoint-url> hdfs:///demo/user s3://my-bucket
----
Consulte `xcp help copy` para obtener más detalles.



== Reanudar

La `resume` el comando reinicia una operación de copia interrumpida previamente especificando el nombre o número del índice del catálogo. El nombre del índice de catálogo o el número de la operación de copia anterior se almacena en la `<catalog path>:/catalog/indexes` directorio.

*Ejemplo:*

[listing]
----
xcp resume [options] -id <id used for copy>
xcp resume [options] -s3.profile <s3 profile name> -s3.endpoint <endpoint-url> -id <id used for copy>
----

NOTE: De forma predeterminada, el XCP `resume` El comando utiliza el punto final S3 y el perfil S3 del índice de copia que se utilizó durante el `copy` comando. Sin embargo, si es nuevo `-s3.endpoint` y.. `-s3.profile` los valores se proporcionan con el `resume` comando, se utilizan los nuevos valores para las opciones y los valores utilizados con la copia `command` se han anulado.

Consulte `xcp help resume` para obtener más detalles.



== Verificación

La `verify` el comando usa una comparación completa de datos byte por byte entre los directorios de origen y destino después de la operación de copia sin usar un número de índice de catálogo. El comando lee los archivos en ambos lados y compara los datos.

*Ejemplo:*

[listing]
----
xcp verify hdfs:///demo/user dst_server:/dst_export
----
*Ejemplo de ruta POSIX:*

[listing]
----
xcp verify hdfs:///user/demo1/data file:///user/demo1/dest
----
*Ejemplo de ruta S3:*

[listing]
----
xcp verify hdfs:///user/demo1/data s3://my-bucket
xcp verify -s3.profile <s3 profile name> -s3.endpoint <endpoint-url> hdfs:///demo/user s3://my-bucket
----
Consulte `xcp help verify` para obtener más detalles.
