---
sidebar: sidebar 
permalink: xcp-nfs-reference-estimate.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Referencia de comandos NFS XCP 
---
= estimación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El NFS de XCP `estimate` el comando se utiliza para estimar el tiempo necesario para completar una copia de referencia del origen al destino. Calcula el tiempo estimado para completar una copia de referencia utilizando todos los recursos del sistema disponibles actualmente, como CPU, RAM, Red y otros parámetros. Puede utilizar el `-target` opción para iniciar una operación de copia de muestra y obtener el tiempo de estimación.

.Sintaxis
[source, cli]
----
xcp estimate -id <name>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.10.10:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.10.10:/temp4' to
'10.101.10.10:/temp8'...
estimate regular file copy task completed before the 1m40s duration
0 in (0/s), 0 out (0/s), 5s
0 in (0/s), 0 out (0/s), 10s
Estimated time to copy '10.101.12.11:/temp4' to '10.101.12.10:/temp8' based on a 1m40s live test:
5.3s
Xcp command : xcp estimate -t 100 -id estimate01 -target 10.101.12.10:/temp8
Estimated Time : 5.3s
Job ID : Job_2023-04-12_08.09.16.126908_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====
En la siguiente tabla, se muestra el `estimate` parámetros y su descripción.

[cols="2*"]
|===
| Parámetro | Descripción 


| <<nfs_estimate_id,estim -id   >> | Especifica el nombre del catálogo de una copia anterior o un índice de exploración. 


| <<nfs_estimate_gbit,estime -gbit   >> | Utiliza gigabits de ancho de banda para estimar el tiempo de mejor caso (valor predeterminado: 1). 


| <<nfs_estimate_target,estime -target   >> | Especifica el destino que se utilizará para la copia de prueba activa. 


| <<nfs_estimate_t,estime -t /s/m/h]>  | Especifica la duración de la copia de prueba en tiempo real (valor predeterminado: 5m). 


| <<nfs_estimate_bs,estime -bs [k]>  | Especifica el tamaño del bloque de lectura/escritura (valor predeterminado: 64K). 


| <<nfs_estimate_dircount,estime -dircount [k]>   | Especifica el tamaño de solicitud para leer directorios (valor por defecto: 64K). 


| <<nfs_estimate_preserveatime,estime -preserve-atime >> | Conserva la hora de acceso del archivo o directorio (valor por defecto: False). 


| <<nfs_estimate_loglevel,estime -loglevel  >> | Establece el nivel de log; los niveles disponibles son INFO, DEBUG (por defecto: INFO) 
|===


== estim -id <name>

Utilice la `-id <name>` con el `estimate` comando para excluir los archivos y directorios que coinciden con el filtro.

.Sintaxis
[source, cli]
----
xcp estimate -id <name>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id csdata01

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 62.0 MiB free space.
Job ID: Job_2023-04-20_12.59.31.260914_estimate
== Best-case estimate to copy ‘data-set:/user1given 1 gigabit of bandwidth ==
112 TiB of data at max 128 MiB/s: at least 10d13h
Xcp command : xcp estimate -id csdata01
Estimated Time : 10d13h
Job ID : Job_2023-04-20_12.59.31.260914_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_12.59.31.260914_estimate.log
STATUS : PASSED
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 62.0 MiB free space.
[root@client1 linux]#
----
====


== estimación - <n> de gbit

Utilice la `-gbit <n>` con el `estimate` comando para estimar el tiempo de mejor caso (valor predeterminado: 1). Esta opción no se puede utilizar con el `-target` opción.

.Sintaxis
[source, cli]
----
xcp estimate -gbit <n> -id <name>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -gbit 10 -id estimate01

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-12_08.12.28.453735_estimate
== Best-case estimate to copy '10.101.12.11:/temp4' given 10 gigabits of bandwidth ==
0 of data at max 1.25 GiB/s: at least 0.0s
Xcp command : xcp estimate -gbit 10 -id estimate01
Estimated Time : 0.0s
Job ID : Job_2023-04-12_08.12.28.453735_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.12.28.453735_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== estimate -target <path>

Utilice la `-target <path>` con el `estimate` comando para especificar el destino que se utilizará para la copia de prueba activa.

.Sintaxis
[source, cli]
----
xcp estimate -t 100 -id <name> -target <path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.12.11:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.12.11:/temp4' to '10.101.12.11:/temp8'...
estimate regular file copy task completed before the 1m40s duration
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== estimación -t <n[s|m|h]>

Utilice la `-t <n[s|m|h]>` con el `estimate` comando para especificar la duración de la copia de prueba en funcionamiento. El valor predeterminado es 5m.

.Sintaxis
[source, cli]
----
xcp estimate -t <n[s|m|h]> -id <name> -target <path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.12.12:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.12.11:/temp4' to
'10.101.12.12:/temp8'...
estimate regular file copy task completed before the 1m40s duration
0 in (0/s), 0 out (0/s), 5s
0 in (0/s), 0 out (0/s), 10s
Estimated time to copy '10.101.12.11:/temp4' to '10.101.12.12:/temp8' based on a 1m40s live
test: 5.3s

Xcp command : xcp estimate -t 100 -id estimate01 -target 10.101.12.11:/temp8
Estimated Time : 5.3s
Job ID : Job_2023-04-12_08.09.16.126908_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== estime -bs <n[k]>

Utilice la `-bs <n[k]>` con el `estimate` comando para especificar el tamaño del bloque de lectura/escritura. El valor predeterminado es 64k.

.Sintaxis
[source, cli]
----
xcp estimate -id <name> -bs <n[k]>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id estimate01 -bs 128k

xcp: WARNING: your license will expire in less than 7 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-24_08.44.12.564441_estimate
63.2 KiB in (12.5 KiB/s), 2.38 KiB out (484/s), 5s
== Best-case estimate to copy 'xxx' given 1 gigabit of bandwidth ==
112 TiB of data at max 128 MiB/s: at least 10d13h
Xcp command : xcp estimate -id estimate01 -bs 128k
Estimated Time : 10d13h
Job ID : Job_2023-04-24_08.44.12.564441_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-24_08.44.12.564441_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== estime -dircount <n[k]>

Utilice la `-dircount <n[k]>` con el `estimate` comando para especificar el tamaño solicitado para la lectura de directorios. El valor predeterminado es 64k.

.Sintaxis
[source, cli]
----
xcp estimate -id <name> -dircount <n[k]> -t <n> -target <path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id csdata01 -dircount 128k -t 300 -target <path>

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 61.6 MiB free space.
Job ID: Job_2023-04-20_13.03.46.820673_estimate
Starting live test for 5m0s to estimate time to copy ‘data-set:/user1 to `<path>`...
1,909 scanned, 126 copied, 2 giants, 580 MiB in (115 MiB/s), 451 MiB out (89.5 MiB/s), 5s
1,909 scanned, 134 copied, 2 giants, 1.23 GiB in (136 MiB/s), 1015 MiB out (112 MiB/s), 10s
1,909 scanned, 143 copied, 2 giants, 1.88 GiB in (131 MiB/s), 1.54 GiB out (113 MiB/s), 15s
.
.
.
7,136 scanned, 2,140 copied, 4 linked, 8 giants, 33.6 GiB in (110 MiB/s), 32.4 GiB out (110
MiB/s), 4m57s
Sample test copy completed for, 300.03s
0 in (-7215675436.180/s), 0 out (-6951487617.036/s), 5m2s
2,186 scanned, 610 KiB in (121 KiB/s), 76.9 KiB out (15.3 KiB/s), 5m7s
Estimated time to copy ‘data-set:/user1to '10.01.12.11:/mapr11' based on a 5m0s live test:
7d6h
Xcp command : xcp estimate -id csdata01 -dircount 128k -t 300 -target 10.101.12.11:/mapr11
Estimated Time : 7d6h
Job ID : Job_2023-04-20_13.03.46.820673_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_13.03.46.820673_estimate.log
STATUS : PASSED
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 61.6 MiB free space.
[root@client1 linux]#
----
====


== estimación - <n> paralelo

Utilice la `-parallel <n>` con el `estimate` comando para especificar el núm. máximo de procesos por lotes simultáneos. El valor predeterminado es 7.

.Sintaxis
[source, cli]
----
xcp estimate -loglevel <name> -parallel <n> -id <name>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -loglevel DEBUG -parallel 8 -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.36.45.535209_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth ==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -parallel 8 -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.36.45.535209_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.36.45.535209_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== estime -preserve-atime

Utilice la `-preserve-atime` con el `estimate` comando para conservar la hora de acceso del archivo o directorio. El valor predeterminado es FALSE.

.Sintaxis
[source, cli]
----
xcp estimate -loglevel <name> -preserve-atime -id <name>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp estimate -loglevel DEBUG -preserve-atime -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.19.04.050516_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth
==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -preserve-atime -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.19.04.050516_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.19.04.050516_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== estim -loglevel <name>

Utilice la `-loglevel <name>` con el `estimate` Comando para definir el nivel de log; los niveles disponibles son INFO y DEBUG. El nivel predeterminado es INFO.

.Sintaxis
[source, cli]
----
xcp estimate -loglevel <name> -id <name>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -loglevel DEBUG -parallel 8 -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.36.45.535209_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth ==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -parallel 8 -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.36.45.535209_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.36.45.535209_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====