---
sidebar: sidebar 
permalink: xcp-reference-logging-syslog.html 
keywords: netapp, xcp, reference, event, logging 
summary: Registro XCP 
---
= Habilite el cliente syslog
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP admite un cliente syslog para enviar mensajes de registro de eventos XCP a un receptor syslog remoto para NFS y SMB. Soporta el protocolo UDP usando el puerto predeterminado 514.



== Configure el cliente de syslog para NFS y SMB

Para habilitar el cliente de syslog, es necesario configurar el `syslog` en el `xcpLogConfig.json` Archivo de configuración para NFS y SMB.

En el ejemplo siguiente de configuración del cliente de syslog para NFS y SMB:

[listing]
----
{
"syslog":{
"isEnabled":true,
"level":"INFO",
"serverIp":"10.101.101.d",
"port":514
},
"sanitize":false
}
----


== Opciones de syslog

En la siguiente tabla se muestran las subopciones de syslog y su descripción:

[cols="1,1,1,3"]
|===
| Subopción | Tipo de datos JSON | Valor predeterminado | Descripción 


| `isEnabled` | Booleano | Falso | Esta opción booleana habilita el cliente syslog en XCP. Configuración en
false ignorará la configuración de syslog. 


| `level` | Cadena | INFORMACIÓN | Nivel de filtro de gravedad de mensajes de eventos. La mensajería de eventos admite cinco niveles de gravedad en orden de gravedad decreciente: CRÍTICO, ERROR, ADVERTENCIA, INFORMACIÓN y DEPURACIÓN 


| `serverIp` | Cadena | Ninguno | Esta opción muestra las direcciones IP o los nombres de host del servidor de syslog remoto. 


| `port` | Integrar | 514 | Esta opción es el puerto del receptor de syslog remoto. Puede configurar receptores de syslog para que acepten datagramas de syslog en un puerto diferente con esta opción. El puerto UDP predeterminado es 514. 
|===

IMPORTANT: La `sanitize` la opción no se debe especificar en la configuración «syslog». Esta opción tiene un ámbito global y es común para el registro, el registro de eventos y syslog en la configuración JSON. Si se establece este valor en “true”, se ocultará información confidencial en los mensajes syslog publicados en el servidor syslog.



== Formato del mensaje de syslog

Cada mensaje de syslog que se envía al servidor de syslog remoto por UDP tiene el formato RFC 5424 para NFS y SMB.

En la siguiente tabla se muestra el nivel de gravedad según RFC 5424 compatible con los mensajes syslog para XCP:

|===
| Valores de gravedad | Nivel de gravedad 


| 3 | Error: Condiciones de error 


| 4 | Advertencia: Condiciones de advertencia 


| 6 | Informativo: Mensajes informativos 


| 7 | Debug: Mensajes de nivel de depuración 
|===
En el encabezado syslog para NFS y SMB, la versión tiene un valor de 1 y el valor de utilidad para todos los mensajes para XCP se establece en 1 (mensajes de nivel de usuario):
`<PRI> = syslog facility * 8 + severity value`

.Formato de mensaje syslog de aplicación XCP con un encabezado syslog para NFS:
En la siguiente tabla se muestra una plantilla y un ejemplo de formato de mensaje de syslog con un encabezado syslog para NFS:

|===
| Plantilla | Ejemplo 


 a| 
`<PRI><version> <Time stamp> <hostname> xcp_nfs - - - <XCP message>`
 a| 
`<14>1 2020-07-08T06:30:34.341Z netapp xcp_nfs - - - INFO {"Event ID": 14,
"Event Category": "XCP job status", "Event Type": "XCP scan completion",
"Event Source": "netapp", "Description": "XCP scan is completed by scanning 8
items"}`

|===
.Mensaje de aplicación XCP sin encabezado syslog para NFS
En la siguiente tabla se muestra una plantilla y un ejemplo del formato del mensaje de syslog sin un encabezado syslog para NFS:

|===
| Plantilla | Ejemplo 


 a| 
`<message severity level i.e CRITICAL, ERROR, WARNING, INFO, DEBUG> <XCP event log message>`
 a| 
`INFO {"Event ID": 14, "Event Category": "XCP job status", "Event Type": "XCP scan completion", "Event Source": "netapp", "Description": "XCP scan is completed by scanning 8 items"}`

|===
.Formato de mensaje syslog de aplicación XCP con encabezado syslog para SMB
En la siguiente tabla se muestra una plantilla y un ejemplo de formato de mensaje de syslog con un encabezado de syslog para SMB:

|===
| Plantilla | Ejemplo 


 a| 
`<PRI><version> <Time stamp> <hostname> xcp_smb - - - <XCP message`
 a| 
`<14>1 2020-07-10T10:37:18.452Z bansala01 xcp_smb - - - INFO {"Event ID": 14, "Event Category": "XCP job status", "Event Type": "XCP scan completion", "Event Source": "NETAPP-01", "Description": "XCP scan is completed by scanning 17 items"}`

|===
.Mensaje de aplicación XCP sin encabezado syslog para SMB
En la siguiente tabla se muestra una plantilla y un ejemplo de formato de mensaje de syslog sin un encabezado de syslog para SMB:

|===
| Plantilla | Ejemplo 


 a| 
`<message severity level i.e CRITICAL, ERROR, WARNING, INFO, DEBUG> <XCP event log message>`
 a| 
`NFO {"Event ID": 14, "Event Category": "XCP job status", "Event Type": "XCP scan completion", "Event Source": "NETAPP-01", "Description": "XCP scan is completed by scanning 17items"}`

|===