---
sidebar: sidebar 
permalink: xcp-migrate-data.html 
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify 
summary: Migración de datos 
---
= Migre datos NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Tras planificar la migración con `show` y.. `scan` Comandos, puede migrar los datos NFS.



== Copiar

La `copy` El comando analiza y copia toda la estructura del directorio de origen en una exportación NFSv3 de destino. La `copy` comando requiere tener rutas de origen y destino como variables. Los archivos escaneados y copiados, el rendimiento/velocidad y los detalles de tiempo transcurrido se muestran al final de la operación de copia.

*Ejemplo:*

[listing]
----
xcp copy <source_nfs_export_path> <destination_nfs_export_path>
----
*Ejemplo de ruta POSIX:*

[listing]
----
xcp copy -newid <id> file:///mnt/source file:///mnt/dest
----
Ejecución `xcp help copy` para obtener más detalles.



== Reanudar

La `resume` el comando reinicia una operación de copia interrumpida previamente especificando el nombre o número del índice del catálogo. El nombre o número de índice del catálogo de la operación de copia anterior se almacena en la `<catalog path>:/catalog/indexes` directorio.

*Ejemplo:*

[listing]
----
xcp resume -id <catalog_name>
----
Ejecución `xcp help resume` para obtener más detalles.



== Sincr

La `sync` El comando busca los cambios y modificaciones realizados en un directorio NFS de origen mediante un nombre de código de índice de catálogo o el número de una operación de copia anterior. Los cambios incrementales de origen se copian y aplican al directorio de destino. Los números de índice de catálogo antiguos se sustituyen por uno nuevo [.underline]#después de la operación de sincronización#.

*Ejemplo:*

[listing]
----
xcp sync -id <catalog_name>
----
Ejecución `xcp help sync` para obtener más detalles.



== Verificación

La `verify` el comando usa una comparación completa de datos byte por byte entre los directorios de origen y destino después de la operación de copia sin usar un número de índice de catálogo. El comando comprueba las horas de modificación y otros atributos de archivo o directorio, incluidos los permisos. El comando también lee los archivos en ambos lados y compara los datos.

*Ejemplo:*

[listing]
----
xcp verify <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol
----
*Ejemplo de ruta POSIX:*

[listing]
----
xcp verify file:///mnt/source file:///mnt/dest
----
Ejecución `xcp help verify` para obtener más detalles.



== ISync

La `isync` el comando compara el origen y el destino y sincroniza las diferencias en el destino sin utilizar el índice de catálogo.

*ejemplo*

[listing]
----
xcp isync <source_ip_address>:/src <destination_ip_address>:/dest

----
Puede utilizar `isync` con la `estimate` opción para estimar el tiempo que tarda en `isync` comando para sincronizar los cambios incrementales. La `-id` el parámetro especifica el nombre del catálogo de una operación de copia anterior.


NOTE: Si cambia más del 25% del tamaño del conjunto de datos utilizado, el `isync estimate` es posible que el comando no muestre los resultados esperados.

*ejemplo*

[listing]
----
xcp isync estimate -id <name>
----
Ejecución `xcp help isync` para obtener más detalles.
