---
sidebar: sidebar 
permalink: xcp-run-multiple-jobs-on-same-host.html 
keywords: xcp, configure, nfs, posix, connector 
summary: El conector POSIX ofrece a XCP la capacidad de acceder a cualquier sistema de archivos montado en Linux, como NFSv4, XFS y Veritas. 
---
= Ejecute varios trabajos XCP en el mismo host XCP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir de XCP 1,9.2, puede ejecutar varios trabajos o comandos XCP en un único host XCP, siempre que el host tenga recursos suficientes para cada trabajo. Cuando ejecuta un comando que admite varios trabajos, XCP utiliza una memoria de host mínima para completar el trabajo, lo que crea la capacidad de ejecutar trabajos adicionales en la misma configuración de host.



== Requisitos mínimos del sistema

Para cada trabajo XCP, debe permitir hasta 64GB GB de memoria del host y ocho núcleos para migraciones medianas a grandes.


NOTE: La ejecución de varios trabajos de XCP en el mismo host no es compatible con la migración de datos de SMB.



== Registro

De forma predeterminada, cada trabajo XCP se registra en un archivo de registro independiente que es único para el ID de trabajo. Este mecanismo de registro funciona bien cuando se ejecutan varios trabajos en el mismo host individual. NetApp no recomienda cambiar el `xcpLogConfig.Json` archivo para utilizar un único `xcp.log` Archivo para registrar varios trabajos XCP que se ejecutan en paralelo en el mismo host.



== Comandos admitidos

La ejecución de varios trabajos XCP en el mismo host se admite con los siguientes comandos XCP:

* `scan`
* `copy`
* `resume`
* `verify`
* `isync`
* `chmod`
* `chown`
* `delete`




== Comandos no admitidos

La ejecución de varios trabajos XCP en el mismo host no es compatible con el `sync` comando.
