---
sidebar: sidebar 
permalink: xcp-nfs-reference-chown.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: Referencia de comandos NFS XCP 
---
= chown
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El NFS de XCP `chown` command escanea y cambia la propiedad de todos los archivos para la estructura de directorios dada. La `chown` El comando requiere un recurso compartido NFS o la ruta POSIX como variable. XCP chown cambia recursivamente la propiedad de una ruta determinada. La `chown` El comando muestra el ID de usuario (UID) cambiado para un archivo.

.Sintaxis
[source, cli]
----
xcp chown -user/-group <user-name/group-name> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -user user2 -v 101.101.10.110:/s_v1/smaple_set/D1

Sat Apr 2 23:06:05 2022
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1 from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/1.txt from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/softlink_1.img from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/1.img from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/hardlink_1.img from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/softlink_to_hardlink_1.img from 1001:0 to
1004:0
Xcp command : xcp chown -user user2 -v 101.101.10.110:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (1.82 KiB/s), 1.11 KiB out (923/s)
Total Time : 1s.
STATUS : PASSED
[root@user-1 linux]#
----
====
En la siguiente tabla, se muestra el `chown` parámetros y su descripción.

[cols="2*"]
|===
| Parámetro | Descripción 


| <<nfs_chown_exclude,chown -excluir   >> | Excluye los archivos y directorios que coinciden con el filtro. 


| <<nfs_chown_match,chown -match   >> | Sólo procesa los archivos y directorios que coinciden con el filtro. 


| <<nfs_chown_group,chown -group   >> | Establece el identificador de grupo de Linux (GID) en el origen. 


| <<nfs_chown_user,chown -user  >> | Establece el UID de Linux en el origen. 


| <<nfs_chown_user_from,chown -user-from  >> | Cambia el UID. 


| <<nfs_chown_group_from,chown -group-from   >> | Cambia el GID. 


| <<nfs_chown_reference,chown -reference  >> | Especifica el archivo o punto de directorio al que se hace referencia. 


| <<nfs_chown_v,chown -v >> | Informa de la salida de cada objeto procesado. 
|===


== chown - excluir <filter>

Utilice la `-exclude <filter>` con el `chown` comando para excluir los archivos y directorios que coinciden con el filtro.

.Sintaxis
[source, cli]
----
xcp chown -exclude <filter> -user <user_name> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -exclude "fnm('1.img')" -user user2 101.101.10.210:/s_v1/smaple_set/D1

Excluded: 1 excluded, 0 did not match exclude criteria
Xcp command : xcp chown -exclude fnm('1.img') -user user2101.101.10.210:/s_v1/smaple_set/D1
Stats : 5 scanned, 1 excluded, 5 changed ownership
Speed : 2.10 KiB in (1.75 KiB/s), 976 out (812/s)
Total Time : 1s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown -match <filter>

Utilice la `-match <filter>` con el `chown` comando para procesar sólo los archivos y directorios que coinciden con el filtro.

.Sintaxis
[source, cli]
----
xcp chown -match <filter>  -user <user_name> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -exclude "fnm('1.img')" -user user2 101.101.10.210:/s_v1/smaple_set/D1

Excluded: 1 excluded, 0 did not match exclude criteria
Xcp command : xcp chown -exclude fnm('1.img') -user user2101.101.10.210:/s_v1/smaple_set/D1
Stats : 5 scanned, 1 excluded, 5 changed ownership
Speed : 2.10 KiB in (1.75 KiB/s), 976 out (812/s)
Total Time : 1s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown - grupo <group>

Utilice la `-group <group>` con el `chown` Comando para definir el GID de Linux en el origen.

.Sintaxis
[source, cli]
----
xcp chown -match <filter> -user <user_name> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -group group1 101.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -group group1 101.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (1.92 KiB/s), 1.11 KiB out (974/s)
Total Time : 1s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown - <user> de usuario

Utilice la `-user <user>` con el `chown` Comando para establecer el UID de Linux en el origen.

.Sintaxis
[source, cli]
----
xcp chown -user -user <user_name> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -user user1 102.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -user user1 102.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (3.12 KiB/s), 1.11 KiB out (1.55 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown -user-de <user_from>

Utilice la `-user-from <user_from>` con el `chown` Comando para cambiar el UID.

.Sintaxis
[source, cli]
----
xcp chown -user-from user1 -user <user_name> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -user-from user1 -user user2
101.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -user-from user1 -user user2 102.108.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (2.44 KiB/s), 1.11 KiB out (1.21 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown -grupo-de <group_from>

Utilice la `-group-from <group_from>` con el `chown` Comando para cambiar el GID.

.Sintaxis
[source, cli]
----
xcp chown -group-from <group_name> -group <group_name> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -group-from group1 -group group2
101.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -group-from group1 -group group2
101.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (4.99 KiB/s), 1.11 KiB out (2.47 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown -referencia <reference>

Utilice la `-reference <reference>` con el `chown` comando para especificar el archivo o punto de directorio al que se hace referencia.

.Sintaxis
[source, cli]
----
xcp chown -reference <reference> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -reference 101.101.10.210:/s_v1/smaple_set/D2/2.img 101.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -reference 101.101.10.210:/s_v1/smaple_set/D2/2.img
101.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 3.11 KiB in (6.25 KiB/s), 2.01 KiB out (4.05 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown -v

Utilice la `-v` con el `chown` comando para informar de la salida de cada objeto procesado.

.Sintaxis
[source, cli]
----
xcp chown -user-from <user_name> -v -user <user_name> <source NFS export path>
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -user-from user2 -v -user user1
101.101.10.210:/s_v1/smaple_set/D1

changed ownership of 101.101.10.210:/s_v1/smaple_set/D1 from 1004:1003 to 1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/1.img from 1004:1003 to 1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/1.txt from 1004:1003 to 1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/softlink_1.img from 1004:1003 to
1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/softlink_to_hardlink_1.img from
1004:1003 to 1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/hardlink_1.img from 1004:1003 to
1001:1003
Xcp command : xcp chown -user-from user2 -v -user user1
101.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (2.02 KiB/s), 1.11 KiB out (1.00 KiB/s)
Total Time : 1s.

STATUS : PASSED
[root@user-1]
----
====