---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: Instalar o actualizar File Analytics para NFS 
---
= Instale File Analytics para NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Instalar o actualizar File Analytics para NFS.

.Acerca de esta tarea
Para conocer los requisitos del sistema para NFS, consulte link:xcp-install-xcp-nfs.html["Instale XCP NFS"].

La `configure.sh` Script instala XCP File Analytics en un equipo host de Red Hat Enterprise Linux (RHEL). Como parte de la instalación, el script instala Postgres Database, Apache HTTPD server y otros paquetes requeridos en la máquina Linux host. Para obtener información sobre las versiones de RHEL compatibles específicas, consulte la link:https://mysupport.netapp.com/matrix/["IMT"^]. Puede cambiar o actualizar a una versión más reciente según sea necesario y seguir las directrices de seguridad. Para obtener más información acerca de `configure.sh` script, ejecutar `./configure.sh -h` en la línea de comandos.

.Antes de empezar
* Si se está ejecutando alguna operación XCP, NetApp recomienda que complete las operaciones antes de iniciar la configuración.
* El equipo Linux debe estar conectado al servidor de repositorio de Yum o a Internet.
* Si se configura un firewall en el equipo Linux, debe cambiar la configuración del firewall para habilitar el puerto 5030, que utiliza el servicio XCP.


.Pasos
. Instalar o actualizar File Analytics para NFS.
+
[role="tabbed-block"]
====
.Instalar análisis de archivos
--
.. Desplácese hasta la `xcp` y ejecute `./configure.sh` guión.
+
Si la instalación se realiza correctamente, se muestra el siguiente mensaje:

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
+

NOTE: Puede utilizar este nombre de usuario y contraseña para iniciar sesión en la GUI de File Analytics.



--
.Actualizar análisis de archivos
--
.. Desplácese hasta la `xcp` carpeta y ejecución `./configure.sh -f`.
.. Introduzca, en el aviso del `y` para limpiar y volver a configurar el sistema.
+
Una vez aprobado el script, limpia la configuración existente y vuelve a configurar el sistema.

+
Si se realiza correctamente, se muestra el siguiente mensaje:

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----


--
====
. Inicie el análisis de archivos en un navegador compatible: *\https://<ip address of linux>/xcp*.
+
Consulte link:xcp-install-xcp-nfs.html["Instale XCP NFS"] para obtener información sobre los navegadores compatibles.


