---
sidebar: sidebar 
permalink: xcp-run-multiple-jobs-on-same-host.html 
keywords: xcp, configure, nfs, posix, connector 
summary: El conector POSIX ofrece a XCP la capacidad de acceder a cualquier sistema de archivos montado en Linux, como NFSv4, XFS y Veritas. 
---
= Ejecute varios trabajos XCP en el mismo host XCP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir de XCP 1,9.2, puede utilizar la función «-minmem» para ejecutar varios trabajos o comandos XCP en un único host XCP, siempre que el host tenga recursos suficientes para cada trabajo. Cuando ejecuta un comando que admite la función «-minmem», XCP utiliza una memoria de host mínima para completar el trabajo, lo que crea la capacidad de ejecutar trabajos adicionales en la misma configuración de host.



== Requisitos mínimos del sistema

Para cada trabajo XCP, debe permitir hasta 64GB GB de memoria del host y ocho núcleos para migraciones medianas a grandes.


NOTE: La función «-minmem» no es compatible con la migración de datos de SMB.



== Registro

De forma predeterminada, cada trabajo XCP se registra en un archivo de registro independiente que es único para el ID de trabajo. Este mecanismo de registro funciona bien cuando se ejecutan varios trabajos en el mismo host individual. NetApp no recomienda cambiar el `xcpLogConfig.Json` archivo para utilizar un único `xcp.log` Archivo para registrar varios trabajos XCP que se ejecutan en paralelo en el mismo host.



== Comandos admitidos

La función «-minmem» es compatible con los siguientes comandos XCP:

* `scan`
* `copy`
* `resume`
* `verify`
* `isync`
* `chmod`
* `chown`
* `delete`




== Comandos no admitidos

La función «-minmem» no es compatible con el `sync` comando.



== Ejemplos de comandos

Para utilizar la función «-minmem», debe incluir la opción «-minmem» en el comando XCP como se muestra en los siguientes ejemplos:

* `xcp copy -newid _new ID_ *-minmem* src_server:/src_export dst_server:/dst_export`
* `xcp resume [options] -id *-minmem* _copy ID_`
* `xcp verify *-minmem* src_server:/src_export dst_server:/dst_export`


*Ejemplos de rutas HDFS*:

* `xcp copy *-minmem* hdfs:///user/demo1/data \file:///user/demo1/dest`
* `xcp verify *-minmem* hdfs:///user/demo1/data \file:///user/demo1/dest`
* `xcp copy -minmem hdfs:///user/demo1/data s3://bucket1`


*Ejemplos de ruta POSIX*:

* `xcp copy *-minmem* -newid _new ID_ \file:///mnt/source \file:///mnt/dest`
* `xcp verify *-minmem* \file:///mnt/source \file:///mnt/dest`

