---
sidebar: sidebar 
permalink: xcp-plan-nfs-data-migration.html 
keywords: netapp, xcp, plan, planning, data, migration, migrate, migrating, nfs, smb, file, analytics 
summary: Planifique las migraciones de datos NFS 
---
= Planifique la migración de datos NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Planifique las migraciones de datos NFS.



== Mostrar

La `show` Command consulta los servicios RPC y las exportaciones NFS de uno o varios servidores de almacenamiento. El comando enumera los servicios y exportaciones disponibles con la capacidad libre y usada de cada exportación, seguidos por los atributos raíz de cada exportación.

*Ejemplo:*

* `xcp show <NFS file server IP/FQDN>`
* `xcp show nfs_server01.netapp.com`


Ejecución `xcp help show` para obtener más detalles.



== Exploración

La `scan` El comando explora de forma recursiva todas las rutas exportadas de NFSv3 de origen e imprime las estadísticas de la estructura de archivos al final del análisis. NetApp recomienda poner los montajes de exportación NFS de origen en modo de solo lectura durante la operación de exploración.

*Ejemplo:*

* `xcp scan NFS [server:/export path | file:// ]`
* `xcp scan nfs_server01.netapp.com:/export1`
* `xcp scan \file:///mnt/nfs-source`


Ejecución `xcp help scan` para obtener más detalles.

De forma opcional, utilice Análisis de archivos para ver los resultados gráficamente.
