---
sidebar: sidebar 
permalink: xcp-smb-reference-verify.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: Referencia de comandos de verificación de SMB de XCP 
---
= verificación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La `verify` el comando lee y compara los recursos compartidos de origen y destino y proporciona información sobre lo que es diferente. Puede utilizar el `verify` comando en cualquier origen y destino, independientemente de la herramienta utilizada para realizar la operación de copia o sincronización.

.Sintaxis
[source, cli]
----
xcp verify \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify  \\<IP address of SMB source server>\source_share  \\<IP address of SMB destination server>\dest_share
xcp verify  \\<IP address of SMB source server>\source_share  \\ <IP address of SMB destination server>\dest_share

xcp verify  \\<IP address of SMB source server>\source_share  \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
xcp verify  \\<IP address of SMB source server>\source_share  \\<IP address of SMB destination server>\dest_share
Total Time : 3s
STATUS : PASSED
----
====
En la siguiente tabla, se muestra el `verify` parámetros y su descripción.

[cols="2*"]
|===
| Parámetro | Descripción 


| <<smb_verify_help,verifique -h, --help>> | Muestre este mensaje de ayuda y salga. 


| <<verifique -v>> | Aumente la verbosidad de la depuración. 


| <<smb_verify_parallel,verificar -paralelo  >> | Núm. De procesos simultáneos (por defecto: <cpu-count>). 


| <<smb_verify_match,verificar -coincidir  >> | Procese sólo los archivos y directorios que coincidan con el filtro (consulte `xcp help - match` para obtener más detalles). 


| <<smb_verify_exclude,verificar -excluir  >> | Solo excluya archivos y directorios en el filtro. 


| <<verifique -preserve-atime>> | Restaurar fecha de último acceso en origen. 


| <<verifique -nodata>> | No compruebe los datos. 


| <<verifique -atime>> | Verifique la hora de acceso al archivo. 


| <<verifique -noctime>> | No compruebe la hora de creación del archivo. 


| <<verifique -nomtime>> | No compruebe la hora de modificación del archivo. 


| <<verifique -noattrs>> | No compruebe los atributos. 


| <<verifique -noownership>> | No comprobar la propiedad. 


| <<verifique -ads>> | Busque cambios y modificaciones de flujos de datos alternativos en el recurso compartido SMB de origen y destino. Si hay cambios, aplica el cambio al destino a.
asegúrese de que el destino es idéntico al origen. 


| <<verifique -noacls>> | No compruebe las ACL. 


| <<verify_smb_atime,verificar -atimewindow  >> | Diferencia de tiempo de acceso aceptable, en segundos. 


| <<verify_smb_ctime,verificar -ctimewindow  >> | Diferencia de tiempo de creación aceptable, en segundos. 


| <<verify_smb_mtime,verificar -mtimewindow  >> | Diferencia de tiempo de modificación aceptable, en segundos, 


| <<verifique -stats>> | Escanee los árboles de origen y de destino en paralelo y compare las estadísticas de árbol. 


| <<verifique -l>> | Aumenta los detalles de salida. 


| <<verifique -ll>> | Aumenta el detalle de salida (formato git diff). 


| <<verify_smb_acl,verifique -fallback-user  >> | Usuario de Active Directory o usuario local (no de dominio) en el equipo de destino para recibir los permisos de los usuarios de la máquina de origen locales (no de dominio) (ejemplo: Dominio\administrador). 


| <<verify_smb_acl,verifique -fallback-group  >> | Grupo de Active Directory o grupo local (no de dominio) en el equipo de destino para recibir los permisos de grupos de máquinas de origen locales (no de dominio) (ejemplo: Dominio\administradores). 


| <<smb_verify_root,verifique -root>> | Sincronizar ACL para el directorio raíz. 


| <<verify_smb_onlyacl,verifique -onlyacl>> | Copie solo la información de seguridad. 
|===


== verifique -h, --help

Utilice la `-h` y.. `–-help` parámetros con el `verify` comando para mostrar información detallada acerca del `verify` comando

.Sintaxis
[source, cli]
----
xcp verify –help
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp verify –help
usage: xcp verify [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>][-preserve-atime]
[-loglevel <name>] [-fallback-user FALLBACK_USER]
[-fallback-group FALLBACK_GROUP] [-noacls] [-nodata] [-stats] [-l] [-root] [-noownership] [-onlyacl] [-noctime] [-nomtime] [-noattrs] [-atime]
[-atimewindow <float>] [-ctimewindow <float>] [-mtimewindow <float>] [-ads] source target

Note: ONTAP does not let a SMB client modify COMPRESSED or ENCRYPTED attributes. XCP sync will ignore these file attributes.

positional arguments:
   source
   target

optional arguments:
-h, --help	           show this help message and exit
-v	                    increase debug verbosity
-parallel <n>	        number of concurrent processes (default: <cpu-count>)
-match <filter>        only process files and directories that match the filter (see `xcp help -match` for details)
-exclude <filter>      Exclude files and directories that match the filter (see `xcp help -exclude` for details)
-preserve-atime	     restore last accessed date on source
--help-diag           Show all options including diag.The diag options should be used only on recommendation by NetApp support.
-loglevel <name>	     option to set log level filter (default:INFO)
-fallback-user FALLBACK_USER
                       a user on the target machine to translate the permissions of local (non-domain) source machine users (eg. domain\administrator)
-fallback-group FALLBACK_GROUP
                       a group on the target machine to translate the permissions of local (non- domain) source machine groups (eg. domain\administrators)
-nodata	              do not check data
-stats	              scan source and target trees in parallel and compare tree statistics
-l	                    detailed file listing output
-root	                 verify acl for root directory
-noacls	              do not check acls
-noownership	        do not check ownership
-onlyacl	              verify only acls
-noctime	              do not check file creation time
-nomtime	              do not check file modification time
-noattrs	              do not check attributes
-atime	              verify acess time as well
-atimewindow <float>   acceptable access time difference in seconds
-ctimewindow <float>   acceptable creation time difference in seconds
-mtimewindow <float>   acceptable modification time difference in seconds
-ads	                 verify ntfs alternate data stream
----
====


== verifique -v

Utilice la `-v` con el `verify` comando para proporcionar información detallada de depuración.

.Sintaxis
[source, cli]
----
xcp verify -v \\<IP address of SMB source server>\source_share address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp> xcp verify -v \\<IP address of SMB source server>\source_share address of SMB destination server>\dest_share
xcp verify -v  \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -v \\< IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique la <n> paralela

Utilice la `-parallel <n>` con el `verify` Comando para definir un Núm. Mayor o menor de procesos simultáneos XCP. La `verify -parallel <n>` el comando verifica el núm. de procesos simultáneos (por defecto: <cpu-count>).


NOTE: El valor máximo de n es 61.

.Sintaxis
[source, cli]
----
xcp verify -v -parallel <n> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -v -parallel 8 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -v -parallel 8 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -v -parallel 8 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 4s
STATUS : PASSED
----
====


== verifique -match <filter>

Utilice la `-match <filter>` con el `verify` comando para explorar el árbol de origen y de destino y comparar sólo los archivos o directorios que coinciden con el argumento de filtro. Si hay alguna diferencia, el comando aplica las acciones necesarias en el destino para mantenerlos sincronizados.

.Sintaxis
[source, cli]
----
xcp verify -v -match <filter> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -v -match "'Microsoft' in name" \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -v -match "'Microsoft' in name" \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -v -match 'Microsoft' in name \\<IP address of SMB source server> \source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 0 compared, 0 same, 0 different, 0 missing, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


== verifique -excluir <filter>

Utilice la `-exclude <filter>` con el `verify` comando para excluir sólo archivos y directorios en el filtro.

.Sintaxis
[source, cli]
----
xcp verify -exclude <filter> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp verify -exclude "path('*Exceptions*')" \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share

210 scanned, 99 excluded, 6 compared, 5 same, 1 different, 0 missing, 0 errors, 5s
210 scanned, 107 excluded, 13 compared, 12 same, 1 different, 0 missing, 0 errors, 10s
210 scanned, 107 excluded, 13 compared, 12 same, 1 different, 0 missing, 0 errors, 15s
210 scanned, 107 excluded, 13 compared, 12 same, 1 different, 0 missing, 0 errors, 20s
335 scanned, 253 excluded, 13 compared, 12 same, 1 different, 0 missing, 0 errors, 25s
445 scanned, 427 excluded, 15 compared, 14 same, 1 different, 0 missing, 0 errors, 30s
445 scanned, 427 excluded, 15 compared, 14 same, 1 different, 0 missing, 0 errors, 35s
445 scanned, 427 excluded, 15 compared, 14 same, 1 different, 0 missing, 0 errors, 40s
445 scanned, 427 excluded, 15 compared, 14 same, 1 different, 0 missing, 0 errors, 45s
445 scanned, 427 excluded, 16 compared, 15 same, 1 different, 0 missing, 0 errors, 50s
xcp verify -exclude path('*Exceptions*') \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share
445 scanned, 427 excluded, 17 compared, 17 same, 0 different, 0 missing, 0 errors
Total Time : 1m11s
STATUS : PASSED
----
====


== verifique -preserve-atime

Utilice la `-preserve-atime` con el `verify` comando para restablecer `atime` Al valor original antes de que XCP lea el archivo.

.Sintaxis
[source, cli]
----
xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

374 scanned, 179 compared, 179 same, 0 different, 0 missing, 0 errors, 5s
xcp verify -preserve-atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 8s
STATUS : PASSED
----
====


== verifique -nodata

Utilice la `-nodata` con el `verify` comando para no comparar datos.

.Sintaxis
[source, cli]
----
xcp verify -nodata \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -nodata \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -nodata \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -nodata \\<IP address of SMB source server> \source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique -atime

Utilice la `-atime` con el `verify` comando para comparar las marcas de tiempo de acceso al archivo desde el origen hasta el destino.

.Sintaxis
[source, cli]
----
xcp verify -ll -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\Netapp\xcp> xcp verify -ll -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

WARNING: your license will expire in less than one week! You can renew your license at https://xcp.netapp.com
dir1: Changed (atime)
  atime
     - 2023-04-14 10:28:47 (1681482527.564423)
     + 2023-04-14 10:24:40 (1681482280.366317)
dir2: Changed (atime)
  atime
     - 2023-04-14 10:28:47 (1681482527.564424)
     + 2023-04-14 10:24:40 (1681482280.366318)
<root>: Changed (atime)
  atime
     - 2023-04-14 10:28:47 (1681482527.054403)
     + 2023-04-14 10:28:35 (1681482515.538801)
xcp verify -ll -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
14 scanned, 13 compared, 10 same, 3 different, 0 missing, 0 errors
Total Time : 1s
STATUS : FAILED
----
====


== verifique -noctime

Utilice la `-noctime` con el `verify` comando para no comparar las marcas de tiempo de creación del archivo desde el origen hasta el destino.

.Sintaxis
[source, cli]
----
xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -noctime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique -nomtime

Utilice la `-nomtime` con el `verify` comando para no comparar las marcas de tiempo de modificación del archivo desde el origen hasta el destino.

.Sintaxis
[source, cli]
----
xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -nomtime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique -noattrs

Utilice la `-noattrs` con el `verify` comando para no comprobar atributos.

.Sintaxis
[source, cli]
----
xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -noattrs \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique -noownership

Utilice la `-noownership` con el `verify` comando para no comprobar la propiedad.

.Sintaxis
[source, cli]
----
xcp verify -noownership \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -noownership \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -noownership	\\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -noownership \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share : PASSED
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique -ads

Uso `-ads` con el `verify` comando para leer si hay flujos de datos alternativos en el origen y el destino y mostrar las diferencias.

.Sintaxis
[source, cli]
----
xcp verify -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	10s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	1m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	1m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	2m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	2m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	2m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	3m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	3m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	3m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	4m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	5m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	5m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	5m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	6m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	6m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	6m10s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	7m0s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	7m5s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	7m55s
7	scanned,	5	compared,	5	same,	0	different,	0	missing,	0	errors,	8m0s

xcp verify -ads \\source_Ip_address>\source_share\src \\<dest_IP_address>\dest_share
7 scanned, 6 compared, 6 same, 0 different, 0 missing, 0 errors
Total Time : 8m4s
STATUS : PASSED
----
====


== verifique -noacls

Utilice la `-noacls` con el `verify` Comando para no comprobar las ACL.

.Sintaxis
[source, cli]
----
xcp verify -noacls -noownership \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -noacls -noownership \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -noacls -noownership	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -noacls -noownership \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
318 scanned, 317 compared, 317 same, 0 different, 0 missing, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


=== verifique -noacls -noownership

Utilice la `-noownership` parámetro con `verify -noacls`  Para no comprobar las ACL ni la propiedad del origen al destino.

.Sintaxis
[source, cli]
----
xcp verify -noacls -noownership <source> <target>
----


== verifique -atimewindow <float>

Utilice la `-atimewindow <float>` con el `verify` comando para especificar la diferencia aceptable, en segundos, para el `atime` de un archivo desde el origen hasta el destino. XCP no informa de que los archivos sean diferentes si la diferencia en `atime` es menor que <value>. La `verify - atimewindow` el comando sólo se puede utilizar con el `-atime` bandera.

.Sintaxis
[source, cli]
----
xcp verify -atimewindow <float> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\Netapp\xcp> xcp verify -atimewindow 600 -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -atimewindow 600 -atime \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

14 scanned, 13 compared, 13 same, 0 different, 0 missing, 0 errors
----
====


== verifique -ctimewindow <float>

Utilice la `-ctimewindow <float>` con el `verify` comando para especificar la diferencia aceptable, en segundos, para el `ctime` de un archivo desde el origen hasta el destino. XCP no informa de que los archivos sean diferentes cuando la diferencia en `ctime` es menor que <value>.

.Sintaxis
[source, cli]
----
xcp verify -ctimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -ctimewindow 600 \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -ctimewindow 600 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -ctimewindow 600 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique -mtimewindow <float>

Utilice la `-mtimewindow <float>` con el `verify` comando para especificar la diferencia aceptable, en segundos, para el `mtime` de un archivo desde el origen hasta el destino. XCP no informa de que los archivos sean diferentes cuando la diferencia en `mtime` es menor que <value>.

.Sintaxis
[source, cli]
----
xcp verify -mtimewindow <float> \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -mtimewindow 600 \\<IP address of SMB sourceserver>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -mtimewindow 600 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -mtimewindow 600 \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique -stats

Utilice la `-stats` con el `verify` comando para escanear el origen y el destino e imprimir un informe de estadísticas de árbol que muestra similitudes o diferencias entre los dos recursos compartidos.

.Sintaxis
[source, cli]
----
xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

       == Number of files ==
	            empty    <8KiB    8-64KiB    64KiB-1MiB   1-10MiB   10-100MiB   >100MiB
                               81        170            62         2
on-target                    same       same          same      same
on-source                    same       same          same      same

       == Directory entries ==
	            empty	  1-10     10-100	     100-1K	   1K-10K	     >10K
        		                       1             1
on-target                                same          same
on-source			             same	      same

       == Depth ==
                  0-5	  6-10	    11-15	      16-20	   21-100	     >100
	              317
on-target           same
on-source	      same

       == Modified ==
              >1 year	>1 month  1-31 days    1-24 hrs   <1 hour   <15 mins     future    invalid
                  315                                    2
on-target        same                                 same
on-source        same                                 same

Total count: 317 / same / same
Directories: 2 / same / same
Regular files: 315 / same / same
Symbolic links:
Junctions:
Special files:
xcp verify -stats \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
635 scanned, 0 errors Total Time : 1s
STATUS : PASSED
----
====


== verifique -l

Utilice la `-l` con el `verify` comando para mostrar las diferencias entre archivos y directorios en el origen y el destino.

.Sintaxis
[source, cli]
----
xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
En el siguiente ejemplo, durante la copia, no se ha transferido la información de propiedad y puede ver las diferencias en el resultado del comando.

.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -l \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verifique -ll

Utilice la `-ll` con el `verify` comando para mostrar las diferencias detalladas de los archivos o directorios del origen y el destino. El formato es como git diff. El valor rojo es el antiguo del origen y el valor verde es el nuevo del destino.

.Sintaxis
[source, cli]
----
xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -ll \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
374 scanned, 373 compared, 373 same, 0 different, 0 missing, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== verify-fallback-user <fallback_user> -fallback-group <fallback_group>

Utilice la `-fallback-user` y.. `-fallback-group` parámetros con el `verify` Comando para mostrar las diferencias de propiedad y ACL entre archivos y directorios en el origen y el destino.


NOTE: Si utiliza `fallback-user` y.. `fallback-group` Con una operación de copia o sincronización, NetApp recomienda que también utilice el `fallback-user` y.. `fallback-group` parámetros con la operación de verificación.

.Sintaxis
[source, cli]
----
xcp verify -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----


=== verifique -noownership-fallback-user <fallback_user> -fallback-group <fallback_group>

Utilice la `-noownership,` `-fallback-user`, y. `-fallback-group` parámetros con el `verify` Comando para mostrar las diferencias de ACL y omitir la verificación de propiedad entre archivos y directorios en el origen y el destino.

.Sintaxis
[source, cli]
----
xcp verify -noownership -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----


=== verifique -noacls-fallback-user <fallback_user> -fallback-group <fallback_group>

Utilice la `-noacls`, `-fallback-user`, y. `-fallback-group` parámetros con el `verify` Comando para omitir la verificación de las ACL y verificar la propiedad entre los archivos y directorios en el origen y el destino.

.Sintaxis
[source, cli]
----
xcp verify -noacls -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----


== verifique -root

Utilice la `-root` con el `verify` Comando para sincronizar las ACL para el directorio raíz.

.Sintaxis
[source, cli]
----
xcp verify -root -fallback-user <fallback_user> -fallback- group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp verify -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share

xcp verify -l -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
7 scanned, 6 compared, 6 same, 0 different, 0 missing, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


=== verify -onlyacl -fallback-user <fallback_user> -fallback- group <fallback_group>

Utilice la `-onlyacl`, `-fallback-user` y.. `-fallback-group` parámetros con el `verify` comando para comparar sólo la información de seguridad entre el origen y el destino.

.Sintaxis
[source, cli]
----
xcp verify -onlyacl -preserve-atime -fallback-user <fallback_user> -fallback- group <fallback_group> \\<IP address of SMB source server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
C:\Users\ctladmin\Desktop>xcp verify -onlyacl -preserve-atime -fallback-user "DOMAIN\User" -fallback- group "DOMAIN\Group" -ll \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

4,722	scanned,	0 compared, 0 same, 0 different, 0 missing, 0 errors, 5s
7,142	scanned,	120 compared, 120 same, 0 different, 0 missing, 0 errors, 10s
7,142	scanned,	856 compared, 856 same, 0 different, 0 missing, 0 errors, 15s
7,142	scanned,	1,374 compared, 1,374 same, 0 different, 0 missing, 0 errors,	20s
7,142	scanned,	2,168 compared, 2,168 same, 0 different, 0 missing, 0 errors,	25s
7,142	scanned,	2,910 compared, 2,910 same, 0 different, 0 missing, 0 errors,	30s
7,142	scanned,	3,629 compared, 3,629 same, 0 different, 0 missing, 0 errors,	35s
7,142	scanned,	4,190 compared, 4,190 same, 0 different, 0 missing, 0 errors,	40s
7,142	scanned,	4,842 compared, 4,842 same, 0 different, 0 missing, 0 errors,	45s
7,142	scanned,	5,622 compared, 5,622 same, 0 different, 0 missing, 0 errors,	50s
7,142	scanned,	6,402 compared, 6,402 same, 0 different, 0 missing, 0 errors,	55s
7,142	scanned,	7,019 compared, 7,019 same, 0 different, 0 missing, 0 errors,	1m0s

xcp verify -onlyacl -preserve-atime -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" -ll \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
7,142 scanned, 7,141 compared, 7,141 same, 0 different, 0 missing, 0 errors
Total Time : 1m2s
STATUS : PASSED
----
====